---
title: "Progress log"
---

This page was used to track our progress and keep a log of our contributions to the project. We created this after developing our idea to create a running list of the workflow that was needed to complete the project and to demonstrate how each of us contributed to the project.

## Satomi
[Satomi's About Me Page](../index.qmd#satomi-aboutme)


**Contribution log:**

#### Index.qmd Literature Review:

* [x] Find 3 academic publications analyzing song popularity using data
* [x] Analyze publications
* [x] Report Findings on Index.qmd page

#### Index.qmd:

* [x] Create about me page

#### Data Collection:

* [x] Develop code to access top 100 songs playlist from Rolling Stones top 100 songs
* [x] Develop code to access spotify api to get data about top 100 songs
* [x] Develop code to access spotify api to get data about artists of top 100 songs
* [x] Provide comments about process and informative technical markdown cells

#### Data Cleansing:

* [x] Consolodate all raw data csvs into one dataframe
* [x] Use VADER to conduct sentiment analysis of lyrics for songs
* [x] Use NLP methods to collect other data about lyrics of songs
* [x] Find other quantitative data from columns for future analysis
* [x] Write all data to a csv file in a processed data folder
* [x] Provide comments about process and informative technical markdown cells

#### Supervised Learning:

* [x] Conduct classification on ranking of song (top 20 vs not)
* [x] Conduct regression on song popularity
* [x] Analyze results to determine important features contributing to success of song
* [x] Provide comments about process and informative technical markdown cells

#### Report:

* [x] Write about key findings from Supervised Learning sections
* [x] Provide informative visualizations
* [ ] Write conclusion

#### Overall:

* [x] Frequent github pushes
* [x] Frequent github pull requests
* [x] Comment code and explain decisions in technical-details files

## Samyu
[Samyu's About Me Page](../index.qmd#samyu-aboutme)

**Contribution log:**

#### Index.qmd Literature Review:

* [x] Find 3 academic publications analyzing song popularity using data
* [x] Analyze publications
* [x] Report Findings on Index.qmd page

#### Index.qmd:

* [x] Create Landing page for website following instructions on page
* [x] Create about me page

#### Report Introduction:

* [ ] Write Objective

#### Data Collection:

* [x] Develop code to access collect lyrics for top 100 songs from Genius API
* [x] Provide comments about process and informative technical markdown cells

#### EDA:

* [x] Develop visualizations to analyze distributions of quantitative data
* [x] Conduct EDA to understand the characteristics of the most popular songs vs the rest of the songs
* [x] Create visualizations to show any correlations in the data
* [x] Provide comments about process and informative technical markdown cells

#### Unsupervised Learning:

* [ ] Use clustering algorithms to develop clusters based on quantitative data and understand connection to song ranking or popularity
* [ ] Analyze results to determine the characteristics of popular songs
* [ ] Determine if there are clusters that can then be used to make playlists of similar songs
* [ ] Provide comments about process and informative technical markdown cells

#### Report:

* [ ] Write executive summary
* [ ] Write about key insights provided by EDA
* [ ] Write about key insights provided by unsupervised learning
* [ ] Provide informative visualizations
* [ ] Write about Business Implications of key findings
* [ ] Write about Recommendations

#### Overall:

* [x] Frequent github pushes
* [x] Frequent github pull requests
* [x] Comment code and explain decisions in technical-details files